### ISSUE TITLE
关于`all_data_final.npy`

### ISSUE THREAD

**Issue by nicken** [ZanyFun9/2019-BAAI-zhuhu-2nd#1]
请问一下，在`nn_LSTUR.ipynb`及`multi_esim.ipynb`中这个文件`all_data_final.npy`是怎么合并的？能否粘贴出详细代码？感激不尽！

尝试过根据`lgb.ipynb`内的形式合并，但一直卡在储存为`all_data_final.npy`文件这一步（问题总是内存不足，使用的是128G内存的机子）；
也曾试过转存为`all_data_final.pkl`文件，转存的是没问题的，可一旦在模型种调用，会产生一样的问题：内存不足；
也曾试过对pd.Dataframe进行格式转换以减少所占空间，但也一直无用；

**Comment by ZanyFun9** [comment]
all_data_final是所有数值类特征的集合,我上传了新文件:nn_mlp.ipynb,里面是我前期调试测试密集特征使用的文件, 然后里面有all_data_final.npy的合成代码可供参考

**Comment by ZanyFun9** [comment]
> 请问一下，在`nn_LSTUR.ipynb`及`multi_esim.ipynb`中这个文件`all_data_final.npy`是怎么合并的？能否粘贴出详细代码？感激不尽！
> 
> 尝试过根据`lgb.ipynb`内的形式合并，但一直卡在储存为`all_data_final.npy`文件这一步（问题总是内存不足，使用的是128G内存的机子）；
> 也曾试过转存为`all_data_final.pkl`文件，转存的是没问题的，可一旦在模型种调用，会产生一样的问题：内存不足；
> 也曾试过对pd.Dataframe进行格式转换以减少所占空间，但也一直无用；

all_data_final是所有数值类特征的集合,我上传了新文件:nn_mlp.ipynb,里面是我前期调试测试密集特征使用的文件, 然后里面有all_data_final.npy的合成代码可供参考

**Comment by nicken** [comment]
感谢万分！问题解决了，原来是少用了这部分：
```python
from sklearn.preprocessing import MinMaxScaler, StandardScaler
mm = StandardScaler()
alldata = mm.fit_transform(pd.concat([train,test]).replace([np.inf, -np.inf], 0).fillna(0))
```
